### ISSUE TITLE
Render external URLs

### ISSUE THREAD

**Issue by azmeuk** [hakonhagland/sphinx-click-rst-to-ansi-formatter#1]
Currently URLs in that form of  are not rendered:
```sphinx
`link title <https://somewhere.example>`_
```

It would be nice if external URLs were rendered in the same fashion than the `:doc:` links.

What do you think?

**Comment by hakonhagland** [comment]
Hi @azmeuk. Thanks for testing this module. Yes, I have only implemented functionality that I needed yet. The plan is to add things like this when requested/needed :) I will have a look at this.

**Comment by hakonhagland** [comment]
@azmeuk Added a PR to fix this: See #3. Can you test this PR? Then I will merge it if looks ok.
