### ISSUE TITLE
Support for `click.group`

### ISSUE THREAD

**Issue by azmeuk** [hakonhagland/sphinx-click-rst-to-ansi-formatter#2]
Using `make_rst_to_ansi_formatter` with `click.group` breaks:

```python
@click.group(cls=make_rst_to_ansi_formatter(DOC_URL))
def ...
```

```python
Traceback (most recent call last):
  File "/home/eloi/.cache/pypoetry/virtualenvs/scim-cli-fJqJQ5MH-py3.12/bin/scim", line 3, in <module>
    from scim_cli import cli
  File "/home/eloi/dev/yaal/scim-cli/scim_cli/__init__.py", line 27, in <module>
    @cli.command(cls=make_rst_to_ansi_formatter(DOC_URL))
     ^^^^^^^^^^^
AttributeError: 'CustomRstToAnsiFormatter' object has no attribute 'command'
```

**Comment by hakonhagland** [comment]
Thanks for the report! You can use `@click.group(cls=make_rst_to_ansi_formatter(DOC_URL), group=True)` for groups, it is currently mentioned in the docs here:

https://hakonhagland.github.io/sphinx-click-rst-to-ansi-formatter/usage.html

Let me know if this docs can be improved to make this more clear.

**Comment by azmeuk** [comment]
Thank you!
